//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sprites.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sprites.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chronoWalk {
            get {
                object obj = ResourceManager.GetObject("chronoWalk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!-- Generated by darkFunction Editor (www.darkfunction.com) --&gt;
        ///&lt;img name=&quot;chronoWalk.png&quot; w=&quot;256&quot; h=&quot;128&quot;&gt;
        ///  &lt;definitions&gt;
        ///    &lt;dir name=&quot;/&quot;&gt;
        ///      &lt;dir name=&quot;walkUp&quot;&gt;
        ///        &lt;spr name=&quot;stand&quot; x=&quot;36&quot; y=&quot;0&quot; w=&quot;16&quot; h=&quot;33&quot;/&gt;
        ///        &lt;spr name=&quot;rFoot2&quot; x=&quot;0&quot; y=&quot;0&quot; w=&quot;18&quot; h=&quot;33&quot;/&gt;
        ///        &lt;spr name=&quot;rfoot3&quot; x=&quot;0&quot; y=&quot;33&quot; w=&quot;16&quot; h=&quot;35&quot;/&gt;
        ///        &lt;spr name=&quot;lFoot1&quot; x=&quot;0&quot; y=&quot;68&quot; w=&quot;18&quot; h=&quot;32&quot;/&gt;
        ///        &lt;spr name=&quot;lFoot2&quot; x=&quot;18&quot; y=&quot;0&quot; w=&quot;18&quot; h=&quot;33&quot;/&gt;
        ///        &lt;spr name=&quot;lFoot3&quot; x=&quot;18&quot; y=&quot;33&quot; w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string chronoWalk1 {
            get {
                return ResourceManager.GetString("chronoWalk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap megamanSprite {
            get {
                object obj = ResourceManager.GetObject("megamanSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
